// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Portal.Infrastructure.Data;

#nullable disable

namespace Portal.Infrastructure.Migrations
{
    [DbContext(typeof(PortalDbContext))]
    [Migration("20251224104553_HistoryAddProp")]
    partial class HistoryAddProp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Portal.Domain.Entities.Hardwares.CategoryHardware", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ShortTitle")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("CategoriesHardware");
                });

            modelBuilder.Entity("Portal.Domain.Entities.Hardwares.DocumentExternalSystem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ShortTitle")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("DocumentsExternalSystem");
                });

            modelBuilder.Entity("Portal.Domain.Entities.Hardwares.Hardware", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryHardwareId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CombinedInvNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTimeAdd")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("DocumentExternalSystemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileNameImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InventoryNumberExternalSystem")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("MainWarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MarkCode")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NameForLabel")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TTN")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserWarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CategoryHardwareId");

                    b.HasIndex("DocumentExternalSystemId");

                    b.HasIndex("MainWarehouseId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserWarehouseId");

                    b.ToTable("Hardwares");
                });

            modelBuilder.Entity("Portal.Domain.Entities.Hardwares.MarkCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("HardwareId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MarkCodeNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MarkCodeNumber"));

                    b.Property<bool>("Used")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("HardwareId");

                    b.ToTable("MarkCodes");
                });

            modelBuilder.Entity("Portal.Domain.Entities.Hardwares.UserHardware", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HardwareId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("UsersHardware");
                });

            modelBuilder.Entity("Portal.Domain.Entities.History.History", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Annotation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateTimeChanges")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("HardwareId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("HardwareMarkCode")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MainWarehouse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Recipient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RecipientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Responsible")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ResponsibleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Sender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserWarehouse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserWarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("HistoryEntries");
                });

            modelBuilder.Entity("Portal.Domain.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("UserDepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserTokenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("UserDepartmentId");

                    b.HasIndex("UserRoleId");

                    b.HasIndex("UserTokenId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f29533dd-9a3c-4889-d468-08ddd5a47b7a"),
                            Email = "admin@admin.by",
                            FirstName = "",
                            IsActive = true,
                            LastName = "Администратор",
                            PasswordHash = "AQAAAAIAAYagAAAAEEnHKp66I1iY4a6WutPESx3dIQF0V/ITse74a7euQmBiSo8E516lhTSbFbEqJVAKQw==",
                            Patronymic = "",
                            Specialization = "",
                            UserDepartmentId = new Guid("d7fa6b79-cf7b-442e-32e6-08ddd5a32cac"),
                            UserRoleId = new Guid("f29533dd-9a3c-4899-d468-08ddd5a47b7a"),
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("d7fa6b79-cf3b-442e-37e6-08ddd5a32cac"),
                            Email = "user@user.by",
                            FirstName = "",
                            IsActive = true,
                            LastName = "Пользователь",
                            PasswordHash = "AQAAAAIAAYagAAAAEOVSg/5PKFU0eFXRm9R6j5GvdEhsxlIymU+I51+5Y/+gQX+c7AHCeu/ZT5ByOLFk7w==",
                            Patronymic = "",
                            Specialization = "",
                            UserDepartmentId = new Guid("d7fa6b79-cf7b-442e-32e6-08ddd5a32cac"),
                            UserRoleId = new Guid("d7fa6b79-cf7b-442e-37e6-08ddd5a32cac"),
                            Username = "user"
                        });
                });

            modelBuilder.Entity("Portal.Domain.Entities.Users.UserDepartment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ShortTitle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("UserDepartments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d7fa6b79-cf7b-442e-32e6-08ddd5a32cac"),
                            ShortTitle = "",
                            Title = "Отдел по умолчанию"
                        });
                });

            modelBuilder.Entity("Portal.Domain.Entities.Users.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PublicTitle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f29533dd-9a3c-4899-d468-08ddd5a47b7a"),
                            PublicTitle = "Администратор",
                            Title = "admin"
                        },
                        new
                        {
                            Id = new Guid("d7fa6b79-cf7b-442e-37e6-08ddd5a32cac"),
                            PublicTitle = "Пользователь",
                            Title = "user"
                        });
                });

            modelBuilder.Entity("Portal.Domain.Entities.Users.UserToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateTimeExpiredToken")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("Portal.Domain.Entities.Warehouses.MainWarehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<Guid>("UserDepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserDepartmentId");

                    b.ToTable("MainWarehouses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c9006a11-ac35-4df9-0c93-08ddd89f84c8"),
                            Description = "",
                            Title = "Основной склад",
                            UserDepartmentId = new Guid("d7fa6b79-cf7b-442e-32e6-08ddd5a32cac")
                        });
                });

            modelBuilder.Entity("Portal.Domain.Entities.Warehouses.UserWarehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserWarehouses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0588a0e8-fdc8-4310-1850-08ddd8a42ead"),
                            Title = "Склад пользователя по умолчанию",
                            UserId = new Guid("f29533dd-9a3c-4889-d468-08ddd5a47b7a")
                        },
                        new
                        {
                            Id = new Guid("0588a0e8-fdc8-4317-1850-08ddd8a42ead"),
                            Title = "Склад пользователя по умолчанию",
                            UserId = new Guid("d7fa6b79-cf3b-442e-37e6-08ddd5a32cac")
                        });
                });

            modelBuilder.Entity("Portal.Domain.Entities.Hardwares.Hardware", b =>
                {
                    b.HasOne("Portal.Domain.Entities.Hardwares.CategoryHardware", "CategoryHardware")
                        .WithMany("Hardwares")
                        .HasForeignKey("CategoryHardwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Portal.Domain.Entities.Hardwares.DocumentExternalSystem", "DocumentExternalSystem")
                        .WithMany("Hardwares")
                        .HasForeignKey("DocumentExternalSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Portal.Domain.Entities.Warehouses.MainWarehouse", "MainWarehouse")
                        .WithMany("Hardwares")
                        .HasForeignKey("MainWarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Portal.Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.HasOne("Portal.Domain.Entities.Warehouses.UserWarehouse", "UserWarehouse")
                        .WithMany("Hardwares")
                        .HasForeignKey("UserWarehouseId");

                    b.Navigation("CategoryHardware");

                    b.Navigation("DocumentExternalSystem");

                    b.Navigation("MainWarehouse");

                    b.Navigation("User");

                    b.Navigation("UserWarehouse");
                });

            modelBuilder.Entity("Portal.Domain.Entities.Hardwares.MarkCode", b =>
                {
                    b.HasOne("Portal.Domain.Entities.Hardwares.Hardware", "Hardware")
                        .WithMany()
                        .HasForeignKey("HardwareId");

                    b.Navigation("Hardware");
                });

            modelBuilder.Entity("Portal.Domain.Entities.Users.User", b =>
                {
                    b.HasOne("Portal.Domain.Entities.Users.UserDepartment", "UserDepartment")
                        .WithMany("Users")
                        .HasForeignKey("UserDepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Portal.Domain.Entities.Users.UserRole", "UserRole")
                        .WithMany("Users")
                        .HasForeignKey("UserRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Portal.Domain.Entities.Users.UserToken", null)
                        .WithMany("Users")
                        .HasForeignKey("UserTokenId");

                    b.Navigation("UserDepartment");

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("Portal.Domain.Entities.Users.UserToken", b =>
                {
                    b.HasOne("Portal.Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Portal.Domain.Entities.Warehouses.MainWarehouse", b =>
                {
                    b.HasOne("Portal.Domain.Entities.Users.UserDepartment", "UserDepartment")
                        .WithMany("MainWarehouses")
                        .HasForeignKey("UserDepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserDepartment");
                });

            modelBuilder.Entity("Portal.Domain.Entities.Warehouses.UserWarehouse", b =>
                {
                    b.HasOne("Portal.Domain.Entities.Users.User", "User")
                        .WithMany("UserWarehouses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Portal.Domain.Entities.Hardwares.CategoryHardware", b =>
                {
                    b.Navigation("Hardwares");
                });

            modelBuilder.Entity("Portal.Domain.Entities.Hardwares.DocumentExternalSystem", b =>
                {
                    b.Navigation("Hardwares");
                });

            modelBuilder.Entity("Portal.Domain.Entities.Users.User", b =>
                {
                    b.Navigation("UserWarehouses");
                });

            modelBuilder.Entity("Portal.Domain.Entities.Users.UserDepartment", b =>
                {
                    b.Navigation("MainWarehouses");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Portal.Domain.Entities.Users.UserRole", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Portal.Domain.Entities.Users.UserToken", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Portal.Domain.Entities.Warehouses.MainWarehouse", b =>
                {
                    b.Navigation("Hardwares");
                });

            modelBuilder.Entity("Portal.Domain.Entities.Warehouses.UserWarehouse", b =>
                {
                    b.Navigation("Hardwares");
                });
#pragma warning restore 612, 618
        }
    }
}
