// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Portal.Infrastructure.Data;

#nullable disable

namespace Portal.Infrastructure.Migrations
{
    [DbContext(typeof(PortalDbContext))]
    [Migration("20250807112524_DefaultUsers")]
    partial class DefaultUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Portal.Domain.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Portal.Domain.Entities.Hardwares.CategoryHardware", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ShortTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CategoriesHardware");
                });

            modelBuilder.Entity("Portal.Domain.Entities.Hardwares.DocumentExternalSystem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ShortTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DocumentsExternalSystem");
                });

            modelBuilder.Entity("Portal.Domain.Entities.Hardwares.Hardware", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryHardwareId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateTimeAdd")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DocumentExternalSystemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileNameImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InventoryNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InventoryNumber"));

                    b.Property<string>("InventoryNumberExternalSystem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MainWarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TTN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryHardwareId");

                    b.HasIndex("DocumentExternalSystemId");

                    b.HasIndex("MainWarehouseId");

                    b.ToTable("Hardwares");
                });

            modelBuilder.Entity("Portal.Domain.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserRoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f29533dd-9a3c-4889-d468-08ddd5a47b7a"),
                            Email = "admin@admin.by",
                            PasswordHash = "AQAAAAIAAYagAAAAEEnHKp66I1iY4a6WutPESx3dIQF0V/ITse74a7euQmBiSo8E516lhTSbFbEqJVAKQw==",
                            UserRoleId = new Guid("f29533dd-9a3c-4899-d468-08ddd5a47b7a"),
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("d7fa6b79-cf3b-442e-37e6-08ddd5a32cac"),
                            Email = "user@user.by",
                            PasswordHash = "AQAAAAIAAYagAAAAEOVSg/5PKFU0eFXRm9R6j5GvdEhsxlIymU+I51+5Y/+gQX+c7AHCeu/ZT5ByOLFk7w==",
                            UserRoleId = new Guid("d7fa6b79-cf7b-442e-37e6-08ddd5a32cac"),
                            Username = "user"
                        });
                });

            modelBuilder.Entity("Portal.Domain.Entities.Users.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PublicTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f29533dd-9a3c-4899-d468-08ddd5a47b7a"),
                            PublicTitle = "Администратор",
                            Title = "admin"
                        },
                        new
                        {
                            Id = new Guid("d7fa6b79-cf7b-442e-37e6-08ddd5a32cac"),
                            PublicTitle = "Пользователь",
                            Title = "user"
                        });
                });

            modelBuilder.Entity("Portal.Domain.Entities.Users.UserToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateTimeExpiredToken")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("Portal.Domain.Entities.Warehouses.MainWarehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MainWarehouses");
                });

            modelBuilder.Entity("Portal.Domain.Entities.Hardwares.Hardware", b =>
                {
                    b.HasOne("Portal.Domain.Entities.Hardwares.CategoryHardware", "CategoryHardware")
                        .WithMany("Hardwares")
                        .HasForeignKey("CategoryHardwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Portal.Domain.Entities.Hardwares.DocumentExternalSystem", "DocumentExternalSystem")
                        .WithMany("Hardwares")
                        .HasForeignKey("DocumentExternalSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Portal.Domain.Entities.Warehouses.MainWarehouse", "MainWarehouse")
                        .WithMany("Hardwares")
                        .HasForeignKey("MainWarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryHardware");

                    b.Navigation("DocumentExternalSystem");

                    b.Navigation("MainWarehouse");
                });

            modelBuilder.Entity("Portal.Domain.Entities.Users.User", b =>
                {
                    b.HasOne("Portal.Domain.Entities.Users.UserRole", "UserRole")
                        .WithMany("Users")
                        .HasForeignKey("UserRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("Portal.Domain.Entities.Hardwares.CategoryHardware", b =>
                {
                    b.Navigation("Hardwares");
                });

            modelBuilder.Entity("Portal.Domain.Entities.Hardwares.DocumentExternalSystem", b =>
                {
                    b.Navigation("Hardwares");
                });

            modelBuilder.Entity("Portal.Domain.Entities.Users.UserRole", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Portal.Domain.Entities.Warehouses.MainWarehouse", b =>
                {
                    b.Navigation("Hardwares");
                });
#pragma warning restore 612, 618
        }
    }
}
